### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by negreanucalin** [phalcon/zephir-website#4]
"IDE Stubs" section displays a blank page, see: https://phalconphp.com/en/download/stubs

![image](https://cloud.githubusercontent.com/assets/1260573/18463818/63e8470c-7995-11e6-9d60-69a013edfedf.png)

**Comment by sergeyklay** [comment]
This is Phalcon Website issue: https://github.com/phalcon/website
Stub are located here: https://github.com/phalcon/phalcon-devtools

**Comment by sergeyklay** [comment]
@negreanucalin Could you please open the issue in the corresponding repo

**Comment by negreanucalin** [comment]
Sorry I will...though this seems to be website related
